// MOVIES
export const POPULAR_MOVIES = 'POPULAR_MOVIES'
export const UPCOMING_MOVIES = 'UPCOMING_MOVIES'
export const NOW_PLAYING_MOVIES = 'NOW_PLAYING_MOVIES'

// TV SHOWS
export const POPULAR_TV_SHOWS = 'POPULAR_TV_SHOWS'
